.TH crispy\-strife-setup 6
.SH NAME
crispy\-strife-setup \- configuration tool for crispy\-strife
.SH SYNOPSIS
.B crispy\-strife-setup
[OPTIONS]
.SH DESCRIPTION
.PP
Crispy Strife is a modern Strife engine designed to behave
as similar to the original Strife game as is possible.
.PP
.B crispy\-strife-setup
is a tool for configuring Crispy Strife. It provides a menu\-based
interface for the display, joystick, keyboard, mouse, sound and
compatibility settings.
.PP
.B crispy\-strife-setup
can also be used to start and join network games.
.PP
.SH OPTIONS
.TP
\fB-config <file>\fR
Load configuration from the specified file, instead of strife.cfg.
.TP
\fB-extraconfig <file>\fR
Load extra configuration from the specified file, instead of crispy\-strife.cfg.
.SH SEE ALSO
\fBcrispy\-strife\fR(6),
\fBdefault.cfg\fR(5),
\fBcrispy\-strife.cfg\fR(5)
.SH AUTHOR
Chocolate Doom is written and maintained by Simon Howard.
.PP
This manual was written by Jonathan Dowland.
.SH COPYRIGHT
Copyright \(co id Software Inc.
Copyright \(co 2005-8 Simon Howard.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

