# Shared file included by the makefiles used to build packages.
# This contains various information needed by the makefiles,
# and is autogenerated by configure to include various
# necessary details.

# Tools needed:

CC = gcc
OBJDUMP = objdump
STRIP = strip
LDFLAGS =  -lSDL2  -lsamplerate  -lpng16   -lz 

# Package name and version number:

PROGRAM_PREFIX = crispy-
PACKAGE = crispy-doom
PACKAGE_NAME = Crispy Doom
PACKAGE_STRING = Crispy Doom 7.0.0
PACKAGE_TARNAME = crispy-doom
PACKAGE_VERSION = 7.0.0

TARGET_OS = arm

# Documentation files to distribute with packages.

DOC_FILES = README.md        \
            README.Music.md  \
            COPYING.md       \
            NEWS.md

